### ISSUE TITLE
[Public Beta] Valet 4 wishlist

### ISSUE THREAD

**Issue by dfed** [square/Valet#179]
I'll be using this issue to track what we'll want to do in our next major version.

- [x] Allow for customizing kSecAttrService on Mac: https://github.com/square/Valet/issues/140
- [x] Remove Xcode 9 Support: #190 
- [x] Dropping Xcode 10 support: #190 
- [x] Drop Swift 4 support: #191
- [ ] ~Consider renaming SecureEnclaveValet per @gravisman – non-biometric keychain items are also stored in the Secure Enclave under the hood. Proposed name: UserPresenceValet~ This item is being removed, since the current naming aligns with [Apple's documentation](https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_secure_enclave).
- [x] Bring `SinglePromptSecureEnclaveValet` to the tvOS target (LocalAuthentication was enabled in tvOS 10): #191
- [x] Get rid of `Accessibility`'s `always` and `alwaysThisDeviceOnly`, since these values have been deprecated: #197
- [x] Move away from `@discardableResult` and towards a `throws` API. We're already letting folk ignore errors. Let's enable that in a more idiomatic way: #198
- [x] Support keychain [sharing via App Groups](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps) in addition to keychain access groups. #230
- [x] Update README to include migration steps required to update to Valet 4: #221

If you want us to include more action items in this list, please file an issue for the change you'd like, and link that issue to this one.

**Comment by piers12** [comment]
The above are all great suggestions but @dfed are you going to still be involved in maintaining Valet?
It seems that you have joined Airbnb now and being the major contributor to Valet, would be great to know how Valet will be maintained going forward?

**Comment by dfed** [comment]
@piers12, I left Square a few years ago at this point, but I absolutely have been and intend to continue staying involved + helping improve Valet. I'm glad the above list is exciting to you! If there's something in particular you'd like from Valet, please [file an issue](https://github.com/square/Valet/blob/master/Contributing.md) 🙂

**Comment by piers12** [comment]
@dfed that's great to hear. I was deciding on wether to use a third party for using keychain in my iOS app and if so which one. The Swifty response from yourself means I think I'll push ahead with using Valet for my own project. Will let you know if there is anything that I would like Valet to add.
Keep up the great work!

**Comment by dfed** [comment]
I've created [develop--4.0](https://github.com/square/Valet/tree/develop--4.0). Branched off of bb7745c5beac46769a7db817e9810252f9ffa80c. Time to get cracking.

**Comment by dfed** [comment]
We should consider getting rid of `Accessibility`'s `always` and `alwaysThisDeviceOnly` in this breaking change, since these values have been deprecated.

**Comment by dfed** [comment]
Another idea: we could move away from `@discardableResult` and towards a `throw`s API. We're already letting folk ignore errors. Let's consider doing it in a more idiomatic way.

**Comment by dfed** [comment]
We'll also need to add a section to our README to discuss how to update to Valet 4, since there will be a few breaking changes.

**Comment by dfed** [comment]
We may want to stop automagically grabbing the `sharedAccessGroupPrefix` from the keychain in Valet 4.0. We're going to start supporting the significantly more modern App Groups keychain API, which lessens the benefit of being able to programmatically identify the `sharedAccessGroupPrefix`.

What makes `sharedAccessGroupPrefix`-derivation difficult to continue maintaining is that we are no longer utilizing the deprecated `always` accessible API. The complexity can be seen in #197; specifically, deriving the shared access group prefix requires generating a `keychainQuery` to be a failable operation. Would be great to jettison this logic.

**Comment by dfed** [comment]
Valet 4 is now in beta! There is no more expected development on the `develop--4.0` branch. If you feel like being on the bleeding edge, please update and let us know in this issue how the new API is treating you!

**Comment by dfed** [comment]
We just added App Group support (#230) to Valet 4, which included some minor breaking API changes to make migration errors and shared identifier creation more semantic and future-proofed.

The latest sha is tagged with the git tag `4.0.0-rc2`. If you feel like being on the bleeding edge, please update and let us know in this issue how the new API is treating you! Both Square and Airbnb have shipped releases with `4.0.0-rc1` — we'll bump to `rc2` this week (though neither company plans on utilizing App Group functionality immediately).

There is no more planned functionality for Valet 4. If no issues are discovered, I plan on merging and releasing Valet 4 by June 15th.

**Comment by dfed** [comment]
Valet 4.0 is now released!
